CREATE DATABASE Insight

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE Users (
  id UUID DEFAULT uuid_generate_v4(),
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  user_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  user_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE Profile (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES Users(id),
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE,
    skills TEXT[],
    experience TEXT[],
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Resume_Uploads (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES Users(id),
    filename VARCHAR(255),
    status VARCHAR(50),
    analysis JSONB,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


